# Generated by Django 5.2.9 on 2025-12-29 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_content_preference'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField(help_text='poe2scout itemId', unique=True)),
                ('name', models.CharField(max_length=128)),
                ('name_ko', models.CharField(blank=True, help_text='한국어 이름', max_length=128)),
                ('type', models.CharField(blank=True, max_length=64)),
                ('category', models.CharField(choices=[('currency', 'Currency'), ('runes', 'Runes'), ('essences', 'Essences'), ('fragments', 'Fragments'), ('waystones', 'Waystones'), ('omens', 'Omens'), ('breachstones', 'Breachstones'), ('deliriuminstill', 'Delirium Instill'), ('uniques', 'Uniques'), ('accessory', 'Accessory'), ('armour', 'Armour'), ('weapon', 'Weapon'), ('jewel', 'Jewel'), ('other', 'Other')], max_length=32)),
                ('category_api_id', models.CharField(blank=True, help_text='poe2scout categoryApiId', max_length=32)),
                ('icon_url', models.URLField(blank=True, default='')),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('league', models.CharField(default='Fate of the Vaal', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-current_price'],
                'indexes': [models.Index(fields=['category'], name='app_marketi_categor_925f65_idx'), models.Index(fields=['league'], name='app_marketi_league_9b8db0_idx'), models.Index(fields=['name'], name='app_marketi_name_2074fd_idx')],
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.IntegerField(default=0, help_text='시장에 올라온 수량')),
                ('recorded_at', models.DateTimeField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_logs', to='app.marketitem')),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['item', 'recorded_at'], name='app_pricehi_item_id_1915bf_idx')],
                'unique_together': {('item', 'recorded_at')},
            },
        ),
    ]
