# Generated by Django 5.2.9 on 2025-12-29 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_market_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='파밍 방법 이름', max_length=128)),
                ('name_ko', models.CharField(help_text='한국어 이름', max_length=128)),
                ('slug', models.SlugField(help_text='URL용 슬러그', unique=True)),
                ('category', models.CharField(choices=[('mapping', '맵핑'), ('boss', '보스'), ('league', '리그 컨텐츠'), ('crafting', '제작'), ('trading', '거래'), ('mechanic', '메카닉')], max_length=32)),
                ('difficulty', models.CharField(choices=[('beginner', '초보자'), ('intermediate', '중급'), ('advanced', '고급'), ('expert', '전문가')], default='intermediate', max_length=16)),
                ('summary', models.TextField(help_text='요약 설명')),
                ('description', models.TextField(help_text='상세 설명 (마크다운 지원)')),
                ('requirements', models.JSONField(default=list, help_text='필요 조건 리스트')),
                ('recommended_items', models.JSONField(default=list, help_text='추천 아이템/서판 리스트')),
                ('steps', models.JSONField(default=list, help_text='파밍 단계별 가이드')),
                ('tips', models.JSONField(default=list, help_text='팁 리스트')),
                ('estimated_profit_min', models.DecimalField(blank=True, decimal_places=2, help_text='시간당 최소 예상 수익 (Divine)', max_digits=10, null=True)),
                ('estimated_profit_max', models.DecimalField(blank=True, decimal_places=2, help_text='시간당 최대 예상 수익 (Divine)', max_digits=10, null=True)),
                ('investment_required', models.DecimalField(decimal_places=2, default=0, help_text='초기 투자 비용 (Divine)', max_digits=10)),
                ('league', models.CharField(default='Fate of the Vaal', max_length=64)),
                ('is_league_specific', models.BooleanField(default=False, help_text='리그 한정 컨텐츠 여부')),
                ('icon', models.CharField(blank=True, help_text='아이콘 이모지 또는 클래스', max_length=64)),
                ('video_url', models.URLField(blank=True, help_text='유튜브 가이드 영상 URL')),
                ('source_url', models.URLField(blank=True, help_text='출처 URL')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_items', models.ManyToManyField(blank=True, help_text='관련 시장 아이템', related_name='farming_methods', to='app.marketitem')),
            ],
            options={
                'ordering': ['sort_order', '-estimated_profit_max'],
                'indexes': [models.Index(fields=['category'], name='app_farming_categor_f935b4_idx'), models.Index(fields=['difficulty'], name='app_farming_difficu_26cb58_idx'), models.Index(fields=['league'], name='app_farming_league_3ca046_idx')],
            },
        ),
    ]
