# Generated by Django 5.2.9 on 2025-12-29 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_farmingmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmingmethod',
            name='creator_name',
            field=models.CharField(blank=True, help_text='파밍 방법을 알린 크리에이터', max_length=64),
        ),
        migrations.AddField(
            model_name='farmingmethod',
            name='creator_url',
            field=models.URLField(blank=True, help_text='크리에이터 채널 URL'),
        ),
    ]
