# Generated by Django 5.2.9 on 2025-12-29 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_farmingmethod_creator_name_farmingmethod_creator_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmingmethod',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0, help_text='추천 별점 (0-5)'),
        ),
    ]
